### ISSUE TITLE
host at talks.barcampgr.org

### ISSUE THREAD

**Issue by brondsem** [twodarek/barcampgr-teams-bot#18]
@brondsem can set up DNS for it.  https cert would have to be updated on the hosting site though

**Comment by twodarek** [comment]
@brondsem Please update `talks.barcampgr.org` to be a CNAME for `twodarek-barcampgr-teams-bot.eastus.cloudapp.azure.com`.  It's using Let's Encrypt's http-challenge, so I can't add that DNS name to the certificate until DNS is updated

**Comment by brondsem** [comment]
Done just now

**Comment by twodarek** [comment]
@brondsem Thanks!  cert-bot has been updated and a new TLS certificate for talks.barcampgr.org has been issued, so we're all good there!
